### ISSUE TITLE
spawn ETXTBSY on server download

### ISSUE THREAD

**Issue by oblitum** [fannheyward/coc-texlab#118]
I think this is a duplicate of #24, but maybe there should be a solution related to https://github.com/fannheyward/coc-rust-analyzer/issues/115? 

```
[coc.nvim] TexLab Server is not found, downloading...
[coc.nvim] Download TexLab Server success
[coc.nvim] Server TexLab failed to start: spawn ETXTBSY
[coc.nvim] error: UnhandledRejection: spawn ETXTBSY
Error: spawn ETXTBSY
    at ChildProcess.spawn (internal/child_process.js:405:11)
    at Object.spawn (child_process.js:548:9)
    at LatexLanuageClient.createMessageTransports (/home/francisco/.vim/plugged/coc.nvim/build/index.js:54334:57)
```

**Comment by oblitum** [comment]
FWIW, after the error shows up, closing/opening nvim fixes the problem (no downloads anymore, and server is loaded).

**Comment by oblitum** [comment]
I just noticed texlab is creating many instance of chktex more than a hundred, maybe it's broken.

**Comment by oblitum** [comment]
Notice also the traceback presents a code type "Lanuage".
