### ISSUE TITLE
Failed to start service on Apple M1 arm64 built neovim 

### ISSUE THREAD

**Issue by TonyWu20** [fannheyward/coc-texlab#180]
CocInfo gives the log when I opened a tex file:
```
2020-11-25T12:01:06.578 INFO (pid:72920) [services] - TexLab state change: stopped => starting
2020-11-25T12:01:06.583 INFO (pid:72920) [language-client-index] - Language server "texlab" started with 37071
2020-11-25T12:01:06.589 ERROR (pid:72920) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:162:15)
    at writeGeneric (node:internal/stream_base_commons:153:3)
    at Socket._writeGeneric (node:net:763:11)
    at Socket._write (node:net:775:8)
    at writeOrBuffer (node:internal/streams/writable:388:12)
    at Socket.Writable.write (node:internal/streams/writable:333:10)
    at StreamMessageWriter.write (/Users/tonywu/.config/nvim/plugged/coc.nvim/build/index.js:18415:27)
    at /Users/tonywu/.config/nvim/plugged/coc.nvim/build/index.js:17563:35
    at new Promise (<anonymous>)
    at Object.sendRequest (/Users/tonywu/.config/nvim/plugged/coc.nvim/build/index.js:17553:26)
    at Object.initialize (/Users/tonywu/.config/nvim/plugged/coc.nvim/build/index.js:79599:44)
    at a.doInitialize (/Users/tonywu/.config/nvim/plugged/coc.nvim/build/index.js:81714:27)
    at a.initialize (/Users/tonywu/.config/nvim/plugged/coc.nvim/build/index.js:81710:25)
    at /Users/tonywu/.config/nvim/plugged/coc.nvim/build/index.js:81632:25 {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
} undefined
2020-11-25T12:01:06.595 INFO (pid:72920) [services] - TexLab state change: starting => stopped
```
`:checkhealth` about node.js returns
```
## Node.js provider (optional)
  - INFO: Node.js: v15.2.1
  - INFO: Nvim node.js host: /opt/homebrew/Cellar/node/15.2.1/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0
```
The neovim was built from a customized branch for built on Apple Silicon arm64. `:version` returns:
```
NVIM v0.5.0-cd691f2-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmiss
ing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/tonywu/Downloads/neo
vim/build/config -I/Users/tonywu/Downloads/neovim/src -I/Users/tonywu/Downloads/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include -I/opt/homebrew/opt/gettext/include
 -I/Users/tonywu/Downloads/neovim/build/src/nvim/auto -I/Users/tonywu/Downloads/neovim/build/include
Compiled by tonywu@TonyWus-Mac-mini.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by fannheyward** [comment]
TexLab's issue, looks like it doesn't work on M1.

**Comment by TonyWu20** [comment]
Thanks. I compile the texlab by myself with the nightly rust (run as native arm64) and then the coc-texlab started successfully.
