### ISSUE TITLE
Cannot rename environment

### ISSUE THREAD

**Issue by dianlujitao** [fannheyward/coc-texlab#228]
MWE
```tex
\begin{itemize}
  \item Foo
  \item Bar
\end{itemize}
```
Cannot rename `itemize`:
```
2021-07-16T15:06:19.726 INFO (pid:1482167) [attach] - receive notification: rename []
2021-07-16T15:06:19.732 ERROR (pid:1482167) [attach] - Notification error: rename [] ReferenceError: logger is not defined
    at vD.rename (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:253:8283)
    at async _D.cocAction (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:253:40744)
    at async EN.<anonymous> (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:253:42301)
```

**Comment by fannheyward** [comment]
> logger is not defined

This has been fixed in coc.nvim, upgrade your coc to latest release and try again.

**Comment by dianlujitao** [comment]
Here're the errors with coc release https://github.com/neoclide/coc.nvim/commit/bdd11f8bfbe38522e20e49c97739d747c9db5bcf
```
2021-07-27T18:32:47.111 INFO (pid:2484892) [attach] - receive notification: rename []
2021-07-27T18:32:47.121 ERROR (pid:2484892) [handler-rename] - Error: The element can't be renamed.
    at /home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:212:33325
    at async Wb.prepareRename (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:210:24951)
    at async BK.prepareRename (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:211:3956)
    at async vD.rename (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:254:7642)
    at async TD.cocAction (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:254:42180)
    at async _N.<anonymous> (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:254:43786)
```

**Comment by MoetaYuko** [comment]
@fannheyward any updates? still got the error with the latest coc and this plugin😢
```
2022-03-12T17:23:55.224 INFO (pid:246430) [attach] - receive notification: rename []
2022-03-12T17:23:55.230 ERROR (pid:246430) [attach] - Notification error: rename [] Error: The element can't be renamed.
    at /home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:210:33623
    at async Uv.prepareRename (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:209:26050)
    at async F3.prepareRename (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:209:35425)
    at async Ex.rename (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:276:7559)
    at async Bx.cocAction (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:278:34320)
    at async H1.<anonymous> (/home/dianlujitao/.dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:278:35839)
```
