### ISSUE TITLE
Floating build progress doesn't disappear after done

### ISSUE THREAD

**Issue by ywpkwon** [fannheyward/coc-texlab#247]
Below is the screenshot (GIF).
I tried to build a simple latex file. The bottom window shows files in the directory. 

After `CocCommand latex.Build`, I see `Build Success` message and output files in the bottom window, but the progress bar keeps rolling and doesn't disappear. (Although I stopped the recording, but it keeps rolling infinitely.)

![Screencast-2022-06-13T01:17:58-07:00](https://user-images.githubusercontent.com/18429284/173310817-28da68a5-33b2-4a42-b1c2-230bce534fef.gif)

How can I solve this?

`:CocInfo`
```
## versions

vim version: NVIM v0.4.3
node version: v14.17.1
coc.nvim version: 0.0.81-74f26199 2022-06-11 17:54:29 +0800
coc.nvim directory: /home/paul/.vim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2022-06-13T01:30:06.840 INFO (pid:15772) [services] - registered service "languageserver.ccls"
2022-06-13T01:30:06.933 WARN (pid:15772) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at Object.setupErrorHandler (/home/paul/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:5529:42)
    at Object.<anonymous> (/home/paul/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:94:51)
```

**Comment by vimpostor** [comment]
One workaround would be to hide all such messages: https://github.com/neoclide/coc.nvim/issues/2702#issuecomment-1152887389
