### ISSUE TITLE
Server TexLab failed to start

### ISSUE THREAD

**Issue by alexfanqi** [fannheyward/coc-texlab#35]
I installed coc-texlab through cocInstall and the lsp failed to start when I open a new tex file. I have another latex lsp installed but I have disabled it in CocConfig.
`:message shows the following errors
[coc.nvim] TexLab Server is not found, downloading...
[coc.nvim] Download TexLab Server success                                       
[coc.nvim] Server TexLab failed to start: spawn ETXTBSY
[coc.nvim] error: UnhandledRejection: spawn ETXTBSY
Error: spawn ETXTBSY
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:540:9)
    at LatexLanuageClient.createMessageTransports (/home/alexfan/.vim/bundle/coc.nvim/buil
d/index.js:76311:57)
`

**Comment by alexfanqi** [comment]
Sorry, never mind, it fixed itself when I open the file the second time
